/* This index.js file was itself autogenerated; run `make` in kb-styles to rebuild */



module.exports = {
  "colors": {
    "blue": {
      "css": "rgb(51,160,255)",
      "r": 51,
      "g": 160,
      "b": 255
    },
    "blue2": {
      "css": "rgb(102,184,255)",
      "r": 102,
      "g": 184,
      "b": 255
    },
    "blue3": {
      "css": "rgb(168,215,255)",
      "r": 168,
      "g": 215,
      "b": 255
    },
    "blue4": {
      "css": "rgb(230,243,255)",
      "r": 230,
      "g": 243,
      "b": 255
    },
    "orange": {
      "css": "rgb(255,111,33)",
      "r": 255,
      "g": 111,
      "b": 33
    },
    "yellow": {
      "css": "rgb(255,247,90)",
      "r": 255,
      "g": 247,
      "b": 90
    },
    "dark_blue": {
      "css": "rgb(25,80,128)",
      "r": 25,
      "g": 80,
      "b": 128
    },
    "dark_blue2": {
      "css": "rgb(36,112,179)",
      "r": 36,
      "g": 112,
      "b": 179
    },
    "dark_blue3": {
      "css": "rgb(0,27,51)",
      "r": 0,
      "g": 27,
      "b": 51
    },
    "green": {
      "css": "rgb(61,204,142)",
      "r": 61,
      "g": 204,
      "b": 142
    },
    "green2": {
      "css": "rgb(54,179,124)",
      "r": 54,
      "g": 179,
      "b": 124
    },
    "red": {
      "css": "rgb(255,77,97)",
      "r": 255,
      "g": 77,
      "b": 97
    },
    "yellow_green": {
      "css": "rgb(137,168,44)",
      "r": 137,
      "g": 168,
      "b": 44
    },
    "light_grey": {
      "css": "rgb(246,246,246)",
      "r": 246,
      "g": 246,
      "b": 246
    },
    "light_grey2": {
      "css": "rgb(235,235,235)",
      "r": 235,
      "g": 235,
      "b": 235
    },
    "background_light_grey2": {
      "css": "rgb(246,246,246)",
      "r": 246,
      "g": 246,
      "b": 246
    },
    "background_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "brown": {
      "css": "rgb(71,31,17)",
      "r": 71,
      "g": 31,
      "b": 17
    },
    "white10": {
      "css": "rgba(255,255,255,0.100)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.1
    },
    "white10_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white10_on_black": {
      "css": "rgb(25,25,25)",
      "r": 25,
      "g": 25,
      "b": 25
    },
    "white10_on_yellow": {
      "css": "rgb(255,247,106)",
      "r": 255,
      "g": 247,
      "b": 106
    },
    "white10_on_dark_blue": {
      "css": "rgb(48,97,140)",
      "r": 48,
      "g": 97,
      "b": 140
    },
    "white20": {
      "css": "rgba(255,255,255,0.200)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.2
    },
    "white20_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white20_on_black": {
      "css": "rgb(51,51,51)",
      "r": 51,
      "g": 51,
      "b": 51
    },
    "white20_on_yellow": {
      "css": "rgb(255,248,123)",
      "r": 255,
      "g": 248,
      "b": 123
    },
    "white20_on_dark_blue": {
      "css": "rgb(71,115,153)",
      "r": 71,
      "g": 115,
      "b": 153
    },
    "white40": {
      "css": "rgba(255,255,255,0.400)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.4
    },
    "white40_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white40_on_black": {
      "css": "rgb(102,102,102)",
      "r": 102,
      "g": 102,
      "b": 102
    },
    "white40_on_yellow": {
      "css": "rgb(255,250,156)",
      "r": 255,
      "g": 250,
      "b": 156
    },
    "white40_on_dark_blue": {
      "css": "rgb(117,150,178)",
      "r": 117,
      "g": 150,
      "b": 178
    },
    "white60": {
      "css": "rgba(255,255,255,0.600)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.6
    },
    "white60_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white60_on_black": {
      "css": "rgb(153,153,153)",
      "r": 153,
      "g": 153,
      "b": 153
    },
    "white60_on_yellow": {
      "css": "rgb(255,251,189)",
      "r": 255,
      "g": 251,
      "b": 189
    },
    "white60_on_dark_blue": {
      "css": "rgb(163,185,204)",
      "r": 163,
      "g": 185,
      "b": 204
    },
    "white75": {
      "css": "rgba(255,255,255,0.750)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.75
    },
    "white75_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white75_on_black": {
      "css": "rgb(191,191,191)",
      "r": 191,
      "g": 191,
      "b": 191
    },
    "white75_on_yellow": {
      "css": "rgb(255,253,213)",
      "r": 255,
      "g": 253,
      "b": 213
    },
    "white75_on_dark_blue": {
      "css": "rgb(197,211,223)",
      "r": 197,
      "g": 211,
      "b": 223
    },
    "black10": {
      "css": "rgba(0,0,0,0.100)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.1
    },
    "black10_on_white": {
      "css": "rgb(229,229,229)",
      "r": 229,
      "g": 229,
      "b": 229
    },
    "black10_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black10_on_yellow": {
      "css": "rgb(229,222,81)",
      "r": 229,
      "g": 222,
      "b": 81
    },
    "black10_on_dark_blue": {
      "css": "rgb(22,72,115)",
      "r": 22,
      "g": 72,
      "b": 115
    },
    "black20": {
      "css": "rgba(0,0,0,0.200)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.2
    },
    "black20_on_white": {
      "css": "rgb(204,204,204)",
      "r": 204,
      "g": 204,
      "b": 204
    },
    "black20_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black20_on_yellow": {
      "css": "rgb(204,197,72)",
      "r": 204,
      "g": 197,
      "b": 72
    },
    "black20_on_dark_blue": {
      "css": "rgb(20,64,102)",
      "r": 20,
      "g": 64,
      "b": 102
    },
    "black40": {
      "css": "rgba(0,0,0,0.400)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.4
    },
    "black40_on_white": {
      "css": "rgb(153,153,153)",
      "r": 153,
      "g": 153,
      "b": 153
    },
    "black40_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black40_on_yellow": {
      "css": "rgb(153,148,54)",
      "r": 153,
      "g": 148,
      "b": 54
    },
    "black40_on_dark_blue": {
      "css": "rgb(15,48,76)",
      "r": 15,
      "g": 48,
      "b": 76
    },
    "black60": {
      "css": "rgba(0,0,0,0.600)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.6
    },
    "black60_on_white": {
      "css": "rgb(102,102,102)",
      "r": 102,
      "g": 102,
      "b": 102
    },
    "black60_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black60_on_yellow": {
      "css": "rgb(102,98,36)",
      "r": 102,
      "g": 98,
      "b": 36
    },
    "black60_on_dark_blue": {
      "css": "rgb(10,32,51)",
      "r": 10,
      "g": 32,
      "b": 51
    },
    "black75": {
      "css": "rgba(0,0,0,0.750)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.75
    },
    "black75_on_white": {
      "css": "rgb(63,63,63)",
      "r": 63,
      "g": 63,
      "b": 63
    },
    "black75_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black75_on_yellow": {
      "css": "rgb(63,61,22)",
      "r": 63,
      "g": 61,
      "b": 22
    },
    "black75_on_dark_blue": {
      "css": "rgb(6,20,32)",
      "r": 6,
      "g": 20,
      "b": 32
    },
    "brown10": {
      "css": "rgba(71,31,17,0.100)",
      "r": 71,
      "g": 31,
      "b": 17,
      "a": 0.1
    },
    "brown10_on_white": {
      "css": "rgb(236,232,231)",
      "r": 236,
      "g": 232,
      "b": 231
    },
    "brown10_on_black": {
      "css": "rgb(7,3,1)",
      "r": 7,
      "g": 3,
      "b": 1
    },
    "brown10_on_yellow": {
      "css": "rgb(236,225,82)",
      "r": 236,
      "g": 225,
      "b": 82
    },
    "brown10_on_dark_blue": {
      "css": "rgb(29,75,116)",
      "r": 29,
      "g": 75,
      "b": 116
    },
    "brown20": {
      "css": "rgba(71,31,17,0.200)",
      "r": 71,
      "g": 31,
      "b": 17,
      "a": 0.2
    },
    "brown20_on_white": {
      "css": "rgb(218,210,207)",
      "r": 218,
      "g": 210,
      "b": 207
    },
    "brown20_on_black": {
      "css": "rgb(14,6,3)",
      "r": 14,
      "g": 6,
      "b": 3
    },
    "brown20_on_yellow": {
      "css": "rgb(218,203,75)",
      "r": 218,
      "g": 203,
      "b": 75
    },
    "brown20_on_dark_blue": {
      "css": "rgb(34,70,105)",
      "r": 34,
      "g": 70,
      "b": 105
    },
    "brown40": {
      "css": "rgba(71,31,17,0.400)",
      "r": 71,
      "g": 31,
      "b": 17,
      "a": 0.4
    },
    "brown40_on_white": {
      "css": "rgb(181,165,159)",
      "r": 181,
      "g": 165,
      "b": 159
    },
    "brown40_on_black": {
      "css": "rgb(28,12,6)",
      "r": 28,
      "g": 12,
      "b": 6
    },
    "brown40_on_yellow": {
      "css": "rgb(181,160,60)",
      "r": 181,
      "g": 160,
      "b": 60
    },
    "brown40_on_dark_blue": {
      "css": "rgb(43,60,83)",
      "r": 43,
      "g": 60,
      "b": 83
    },
    "brown60": {
      "css": "rgba(71,31,17,0.600)",
      "r": 71,
      "g": 31,
      "b": 17,
      "a": 0.6
    },
    "brown60_on_white": {
      "css": "rgb(144,120,112)",
      "r": 144,
      "g": 120,
      "b": 112
    },
    "brown60_on_black": {
      "css": "rgb(42,18,10)",
      "r": 42,
      "g": 18,
      "b": 10
    },
    "brown60_on_yellow": {
      "css": "rgb(144,117,46)",
      "r": 144,
      "g": 117,
      "b": 46
    },
    "brown60_on_dark_blue": {
      "css": "rgb(52,50,61)",
      "r": 52,
      "g": 50,
      "b": 61
    },
    "brown75": {
      "css": "rgba(71,31,17,0.750)",
      "r": 71,
      "g": 31,
      "b": 17,
      "a": 0.75
    },
    "brown75_on_white": {
      "css": "rgb(117,87,76)",
      "r": 117,
      "g": 87,
      "b": 76
    },
    "brown75_on_black": {
      "css": "rgb(53,23,12)",
      "r": 53,
      "g": 23,
      "b": 12
    },
    "brown75_on_yellow": {
      "css": "rgb(117,85,35)",
      "r": 117,
      "g": 85,
      "b": 35
    },
    "brown75_on_dark_blue": {
      "css": "rgb(59,43,44)",
      "r": 59,
      "g": 43,
      "b": 44
    },
    "blue10": {
      "css": "rgba(51,160,255,0.100)",
      "r": 51,
      "g": 160,
      "b": 255,
      "a": 0.1
    },
    "blue10_on_white": {
      "css": "rgb(234,245,255)",
      "r": 234,
      "g": 245,
      "b": 255
    },
    "blue10_on_black": {
      "css": "rgb(5,16,25)",
      "r": 5,
      "g": 16,
      "b": 25
    },
    "blue10_on_yellow": {
      "css": "rgb(234,238,106)",
      "r": 234,
      "g": 238,
      "b": 106
    },
    "blue10_on_dark_blue": {
      "css": "rgb(27,88,140)",
      "r": 27,
      "g": 88,
      "b": 140
    },
    "blue20": {
      "css": "rgba(51,160,255,0.200)",
      "r": 51,
      "g": 160,
      "b": 255,
      "a": 0.2
    },
    "blue20_on_white": {
      "css": "rgb(214,236,255)",
      "r": 214,
      "g": 236,
      "b": 255
    },
    "blue20_on_black": {
      "css": "rgb(10,32,51)",
      "r": 10,
      "g": 32,
      "b": 51
    },
    "blue20_on_yellow": {
      "css": "rgb(214,229,123)",
      "r": 214,
      "g": 229,
      "b": 123
    },
    "blue20_on_dark_blue": {
      "css": "rgb(30,96,153)",
      "r": 30,
      "g": 96,
      "b": 153
    },
    "blue40": {
      "css": "rgba(51,160,255,0.400)",
      "r": 51,
      "g": 160,
      "b": 255,
      "a": 0.4
    },
    "blue40_on_white": {
      "css": "rgb(173,217,255)",
      "r": 173,
      "g": 217,
      "b": 255
    },
    "blue40_on_black": {
      "css": "rgb(20,64,102)",
      "r": 20,
      "g": 64,
      "b": 102
    },
    "blue40_on_yellow": {
      "css": "rgb(173,212,156)",
      "r": 173,
      "g": 212,
      "b": 156
    },
    "blue40_on_dark_blue": {
      "css": "rgb(35,112,178)",
      "r": 35,
      "g": 112,
      "b": 178
    },
    "blue60": {
      "css": "rgba(51,160,255,0.600)",
      "r": 51,
      "g": 160,
      "b": 255,
      "a": 0.6
    },
    "blue60_on_white": {
      "css": "rgb(132,198,255)",
      "r": 132,
      "g": 198,
      "b": 255
    },
    "blue60_on_black": {
      "css": "rgb(30,96,153)",
      "r": 30,
      "g": 96,
      "b": 153
    },
    "blue60_on_yellow": {
      "css": "rgb(132,194,189)",
      "r": 132,
      "g": 194,
      "b": 189
    },
    "blue60_on_dark_blue": {
      "css": "rgb(40,128,204)",
      "r": 40,
      "g": 128,
      "b": 204
    },
    "blue75": {
      "css": "rgba(51,160,255,0.750)",
      "r": 51,
      "g": 160,
      "b": 255,
      "a": 0.75
    },
    "blue75_on_white": {
      "css": "rgb(102,183,255)",
      "r": 102,
      "g": 183,
      "b": 255
    },
    "blue75_on_black": {
      "css": "rgb(38,120,191)",
      "r": 38,
      "g": 120,
      "b": 191
    },
    "blue75_on_yellow": {
      "css": "rgb(102,181,213)",
      "r": 102,
      "g": 181,
      "b": 213
    },
    "blue75_on_dark_blue": {
      "css": "rgb(44,140,223)",
      "r": 44,
      "g": 140,
      "b": 223
    }
  }
}

