/* This index.js file was itself autogenerated; run `make` in kb-styles to rebuild */



module.exports = {
  "colors": {
    "blue": {
      "css": "rgb(76,142,255)",
      "r": 76,
      "g": 142,
      "b": 255
    },
    "blue2": {
      "css": "rgb(115,166,255)",
      "r": 115,
      "g": 166,
      "b": 255
    },
    "blue3": {
      "css": "rgb(168,204,255)",
      "r": 168,
      "g": 204,
      "b": 255
    },
    "blue4": {
      "css": "rgb(235,242,252)",
      "r": 235,
      "g": 242,
      "b": 252
    },
    "blue5": {
      "css": "rgba(76,142,255,0.050)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.05
    },
    "orange": {
      "css": "rgb(255,111,33)",
      "r": 255,
      "g": 111,
      "b": 33
    },
    "yellow": {
      "css": "rgb(255,247,90)",
      "r": 255,
      "g": 247,
      "b": 90
    },
    "yellow2": {
      "css": "rgb(219,210,42)",
      "r": 219,
      "g": 210,
      "b": 42
    },
    "yellow3": {
      "css": "rgb(255,253,204)",
      "r": 255,
      "g": 253,
      "b": 204
    },
    "dark_blue": {
      "css": "rgb(38,69,163)",
      "r": 38,
      "g": 69,
      "b": 163
    },
    "dark_blue2": {
      "css": "rgb(54,99,234)",
      "r": 54,
      "g": 99,
      "b": 234
    },
    "dark_blue3": {
      "css": "rgb(24,45,110)",
      "r": 24,
      "g": 45,
      "b": 110
    },
    "dark_blue4": {
      "css": "rgb(16,54,172)",
      "r": 16,
      "g": 54,
      "b": 172
    },
    "green": {
      "css": "rgb(55,189,153)",
      "r": 55,
      "g": 189,
      "b": 153
    },
    "green2": {
      "css": "rgb(40,154,114)",
      "r": 40,
      "g": 154,
      "b": 114
    },
    "green3": {
      "css": "rgb(232,250,246)",
      "r": 232,
      "g": 250,
      "b": 246
    },
    "red": {
      "css": "rgb(255,77,97)",
      "r": 255,
      "g": 77,
      "b": 97
    },
    "yellow_green": {
      "css": "rgb(168,207,54)",
      "r": 168,
      "g": 207,
      "b": 54
    },
    "yellow_green2": {
      "css": "rgb(148,181,47)",
      "r": 148,
      "g": 181,
      "b": 47
    },
    "yellow_green3": {
      "css": "rgb(210,230,151)",
      "r": 210,
      "g": 230,
      "b": 151
    },
    "light_grey": {
      "css": "rgb(246,246,246)",
      "r": 246,
      "g": 246,
      "b": 246
    },
    "light_grey2": {
      "css": "rgb(230,230,230)",
      "r": 230,
      "g": 230,
      "b": 230
    },
    "grey": {
      "css": "rgb(204,204,204)",
      "r": 204,
      "g": 204,
      "b": 204
    },
    "beige": {
      "css": "rgb(250,242,237)",
      "r": 250,
      "g": 242,
      "b": 237
    },
    "purple": {
      "css": "rgb(112,78,186)",
      "r": 112,
      "g": 78,
      "b": 186
    },
    "purple2": {
      "css": "rgb(132,92,219)",
      "r": 132,
      "g": 92,
      "b": 219
    },
    "purple3": {
      "css": "rgb(159,123,236)",
      "r": 159,
      "g": 123,
      "b": 236
    },
    "background_light_grey2": {
      "css": "rgb(246,246,246)",
      "r": 246,
      "g": 246,
      "b": 246
    },
    "background_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "brown": {
      "css": "rgb(71,31,18)",
      "r": 71,
      "g": 31,
      "b": 18
    },
    "white5": {
      "css": "rgba(255,255,255,0.050)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.05
    },
    "white5_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white5_on_black": {
      "css": "rgb(12,12,12)",
      "r": 12,
      "g": 12,
      "b": 12
    },
    "white5_on_yellow": {
      "css": "rgb(255,247,98)",
      "r": 255,
      "g": 247,
      "b": 98
    },
    "white5_on_dark_blue": {
      "css": "rgb(48,78,167)",
      "r": 48,
      "g": 78,
      "b": 167
    },
    "white10": {
      "css": "rgba(255,255,255,0.100)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.1
    },
    "white10_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white10_on_black": {
      "css": "rgb(25,25,25)",
      "r": 25,
      "g": 25,
      "b": 25
    },
    "white10_on_yellow": {
      "css": "rgb(255,247,106)",
      "r": 255,
      "g": 247,
      "b": 106
    },
    "white10_on_dark_blue": {
      "css": "rgb(59,87,172)",
      "r": 59,
      "g": 87,
      "b": 172
    },
    "white20": {
      "css": "rgba(255,255,255,0.200)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.2
    },
    "white20_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white20_on_black": {
      "css": "rgb(51,51,51)",
      "r": 51,
      "g": 51,
      "b": 51
    },
    "white20_on_yellow": {
      "css": "rgb(255,248,123)",
      "r": 255,
      "g": 248,
      "b": 123
    },
    "white20_on_dark_blue": {
      "css": "rgb(81,106,181)",
      "r": 81,
      "g": 106,
      "b": 181
    },
    "white50": {
      "css": "rgba(255,255,255,0.500)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.5
    },
    "white50_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white50_on_black": {
      "css": "rgb(127,127,127)",
      "r": 127,
      "g": 127,
      "b": 127
    },
    "white50_on_yellow": {
      "css": "rgb(255,251,172)",
      "r": 255,
      "g": 251,
      "b": 172
    },
    "white50_on_dark_blue": {
      "css": "rgb(146,162,209)",
      "r": 146,
      "g": 162,
      "b": 209
    },
    "white63": {
      "css": "rgba(255,255,255,0.630)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.63
    },
    "white63_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white63_on_black": {
      "css": "rgb(160,160,160)",
      "r": 160,
      "g": 160,
      "b": 160
    },
    "white63_on_yellow": {
      "css": "rgb(255,252,193)",
      "r": 255,
      "g": 252,
      "b": 193
    },
    "white63_on_dark_blue": {
      "css": "rgb(174,186,220)",
      "r": 174,
      "g": 186,
      "b": 220
    },
    "white85": {
      "css": "rgba(255,255,255,0.850)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.85
    },
    "white85_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white85_on_black": {
      "css": "rgb(216,216,216)",
      "r": 216,
      "g": 216,
      "b": 216
    },
    "white85_on_yellow": {
      "css": "rgb(255,253,230)",
      "r": 255,
      "g": 253,
      "b": 230
    },
    "white85_on_dark_blue": {
      "css": "rgb(222,227,241)",
      "r": 222,
      "g": 227,
      "b": 241
    },
    "black5": {
      "css": "rgba(0,0,0,0.050)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.05
    },
    "black5_on_white": {
      "css": "rgb(242,242,242)",
      "r": 242,
      "g": 242,
      "b": 242
    },
    "black5_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black5_on_yellow": {
      "css": "rgb(242,234,85)",
      "r": 242,
      "g": 234,
      "b": 85
    },
    "black5_on_dark_blue": {
      "css": "rgb(36,65,154)",
      "r": 36,
      "g": 65,
      "b": 154
    },
    "black10": {
      "css": "rgba(0,0,0,0.100)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.1
    },
    "black10_on_white": {
      "css": "rgb(229,229,229)",
      "r": 229,
      "g": 229,
      "b": 229
    },
    "black10_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black10_on_yellow": {
      "css": "rgb(229,222,81)",
      "r": 229,
      "g": 222,
      "b": 81
    },
    "black10_on_dark_blue": {
      "css": "rgb(34,62,146)",
      "r": 34,
      "g": 62,
      "b": 146
    },
    "black20": {
      "css": "rgba(0,0,0,0.200)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.2
    },
    "black20_on_white": {
      "css": "rgb(204,204,204)",
      "r": 204,
      "g": 204,
      "b": 204
    },
    "black20_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black20_on_yellow": {
      "css": "rgb(204,197,72)",
      "r": 204,
      "g": 197,
      "b": 72
    },
    "black20_on_dark_blue": {
      "css": "rgb(30,55,130)",
      "r": 30,
      "g": 55,
      "b": 130
    },
    "black50": {
      "css": "rgba(0,0,0,0.500)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.5
    },
    "black50_on_white": {
      "css": "rgb(127,127,127)",
      "r": 127,
      "g": 127,
      "b": 127
    },
    "black50_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black50_on_yellow": {
      "css": "rgb(127,123,45)",
      "r": 127,
      "g": 123,
      "b": 45
    },
    "black50_on_dark_blue": {
      "css": "rgb(19,34,81)",
      "r": 19,
      "g": 34,
      "b": 81
    },
    "black63": {
      "css": "rgba(0,0,0,0.630)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.63
    },
    "black63_on_white": {
      "css": "rgb(94,94,94)",
      "r": 94,
      "g": 94,
      "b": 94
    },
    "black63_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black63_on_yellow": {
      "css": "rgb(94,91,33)",
      "r": 94,
      "g": 91,
      "b": 33
    },
    "black63_on_dark_blue": {
      "css": "rgb(14,25,60)",
      "r": 14,
      "g": 25,
      "b": 60
    },
    "black85": {
      "css": "rgba(0,0,0,0.850)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.85
    },
    "black85_on_white": {
      "css": "rgb(38,38,38)",
      "r": 38,
      "g": 38,
      "b": 38
    },
    "black85_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black85_on_yellow": {
      "css": "rgb(38,37,13)",
      "r": 38,
      "g": 37,
      "b": 13
    },
    "black85_on_dark_blue": {
      "css": "rgb(5,10,24)",
      "r": 5,
      "g": 10,
      "b": 24
    },
    "brown5": {
      "css": "rgba(71,31,18,0.050)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.05
    },
    "brown5_on_white": {
      "css": "rgb(245,243,243)",
      "r": 245,
      "g": 243,
      "b": 243
    },
    "brown5_on_black": {
      "css": "rgb(3,1,0)",
      "r": 3,
      "g": 1,
      "b": 0
    },
    "brown5_on_yellow": {
      "css": "rgb(245,236,86)",
      "r": 245,
      "g": 236,
      "b": 86
    },
    "brown5_on_dark_blue": {
      "css": "rgb(39,67,155)",
      "r": 39,
      "g": 67,
      "b": 155
    },
    "brown10": {
      "css": "rgba(71,31,18,0.100)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.1
    },
    "brown10_on_white": {
      "css": "rgb(236,232,231)",
      "r": 236,
      "g": 232,
      "b": 231
    },
    "brown10_on_black": {
      "css": "rgb(7,3,1)",
      "r": 7,
      "g": 3,
      "b": 1
    },
    "brown10_on_yellow": {
      "css": "rgb(236,225,82)",
      "r": 236,
      "g": 225,
      "b": 82
    },
    "brown10_on_dark_blue": {
      "css": "rgb(41,65,148)",
      "r": 41,
      "g": 65,
      "b": 148
    },
    "brown20": {
      "css": "rgba(71,31,18,0.200)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.2
    },
    "brown20_on_white": {
      "css": "rgb(218,210,207)",
      "r": 218,
      "g": 210,
      "b": 207
    },
    "brown20_on_black": {
      "css": "rgb(14,6,3)",
      "r": 14,
      "g": 6,
      "b": 3
    },
    "brown20_on_yellow": {
      "css": "rgb(218,203,75)",
      "r": 218,
      "g": 203,
      "b": 75
    },
    "brown20_on_dark_blue": {
      "css": "rgb(44,61,134)",
      "r": 44,
      "g": 61,
      "b": 134
    },
    "brown50": {
      "css": "rgba(71,31,18,0.500)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.5
    },
    "brown50_on_white": {
      "css": "rgb(163,143,136)",
      "r": 163,
      "g": 143,
      "b": 136
    },
    "brown50_on_black": {
      "css": "rgb(35,15,9)",
      "r": 35,
      "g": 15,
      "b": 9
    },
    "brown50_on_yellow": {
      "css": "rgb(163,139,54)",
      "r": 163,
      "g": 139,
      "b": 54
    },
    "brown50_on_dark_blue": {
      "css": "rgb(54,50,90)",
      "r": 54,
      "g": 50,
      "b": 90
    },
    "brown63": {
      "css": "rgba(71,31,18,0.630)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.63
    },
    "brown63_on_white": {
      "css": "rgb(139,113,105)",
      "r": 139,
      "g": 113,
      "b": 105
    },
    "brown63_on_black": {
      "css": "rgb(44,19,11)",
      "r": 44,
      "g": 19,
      "b": 11
    },
    "brown63_on_yellow": {
      "css": "rgb(139,110,44)",
      "r": 139,
      "g": 110,
      "b": 44
    },
    "brown63_on_dark_blue": {
      "css": "rgb(58,45,71)",
      "r": 58,
      "g": 45,
      "b": 71
    },
    "brown85": {
      "css": "rgba(71,31,18,0.850)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.85
    },
    "brown85_on_white": {
      "css": "rgb(98,64,53)",
      "r": 98,
      "g": 64,
      "b": 53
    },
    "brown85_on_black": {
      "css": "rgb(60,26,15)",
      "r": 60,
      "g": 26,
      "b": 15
    },
    "brown85_on_yellow": {
      "css": "rgb(98,63,28)",
      "r": 98,
      "g": 63,
      "b": 28
    },
    "brown85_on_dark_blue": {
      "css": "rgb(66,36,39)",
      "r": 66,
      "g": 36,
      "b": 39
    },
    "blue5_on_white": {
      "css": "rgb(246,249,255)",
      "r": 246,
      "g": 249,
      "b": 255
    },
    "blue5_on_black": {
      "css": "rgb(3,7,12)",
      "r": 3,
      "g": 7,
      "b": 12
    },
    "blue5_on_yellow": {
      "css": "rgb(246,241,98)",
      "r": 246,
      "g": 241,
      "b": 98
    },
    "blue5_on_dark_blue": {
      "css": "rgb(39,72,167)",
      "r": 39,
      "g": 72,
      "b": 167
    },
    "blue10": {
      "css": "rgba(76,142,255,0.100)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.1
    },
    "blue10_on_white": {
      "css": "rgb(237,243,255)",
      "r": 237,
      "g": 243,
      "b": 255
    },
    "blue10_on_black": {
      "css": "rgb(7,14,25)",
      "r": 7,
      "g": 14,
      "b": 25
    },
    "blue10_on_yellow": {
      "css": "rgb(237,236,106)",
      "r": 237,
      "g": 236,
      "b": 106
    },
    "blue10_on_dark_blue": {
      "css": "rgb(41,76,172)",
      "r": 41,
      "g": 76,
      "b": 172
    },
    "blue20": {
      "css": "rgba(76,142,255,0.200)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.2
    },
    "blue20_on_white": {
      "css": "rgb(219,232,255)",
      "r": 219,
      "g": 232,
      "b": 255
    },
    "blue20_on_black": {
      "css": "rgb(15,28,51)",
      "r": 15,
      "g": 28,
      "b": 51
    },
    "blue20_on_yellow": {
      "css": "rgb(219,226,123)",
      "r": 219,
      "g": 226,
      "b": 123
    },
    "blue20_on_dark_blue": {
      "css": "rgb(45,83,181)",
      "r": 45,
      "g": 83,
      "b": 181
    },
    "blue50": {
      "css": "rgba(76,142,255,0.500)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.5
    },
    "blue50_on_white": {
      "css": "rgb(165,198,255)",
      "r": 165,
      "g": 198,
      "b": 255
    },
    "blue50_on_black": {
      "css": "rgb(38,71,127)",
      "r": 38,
      "g": 71,
      "b": 127
    },
    "blue50_on_yellow": {
      "css": "rgb(165,194,172)",
      "r": 165,
      "g": 194,
      "b": 172
    },
    "blue50_on_dark_blue": {
      "css": "rgb(57,105,209)",
      "r": 57,
      "g": 105,
      "b": 209
    },
    "blue63": {
      "css": "rgba(76,142,255,0.630)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.63
    },
    "blue63_on_white": {
      "css": "rgb(142,183,255)",
      "r": 142,
      "g": 183,
      "b": 255
    },
    "blue63_on_black": {
      "css": "rgb(47,89,160)",
      "r": 47,
      "g": 89,
      "b": 160
    },
    "blue63_on_yellow": {
      "css": "rgb(142,180,193)",
      "r": 142,
      "g": 180,
      "b": 193
    },
    "blue63_on_dark_blue": {
      "css": "rgb(61,114,220)",
      "r": 61,
      "g": 114,
      "b": 220
    },
    "blue85": {
      "css": "rgba(76,142,255,0.850)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.85
    },
    "blue85_on_white": {
      "css": "rgb(102,158,255)",
      "r": 102,
      "g": 158,
      "b": 255
    },
    "blue85_on_black": {
      "css": "rgb(64,120,216)",
      "r": 64,
      "g": 120,
      "b": 216
    },
    "blue85_on_yellow": {
      "css": "rgb(102,157,230)",
      "r": 102,
      "g": 157,
      "b": 230
    },
    "blue85_on_dark_blue": {
      "css": "rgb(70,131,241)",
      "r": 70,
      "g": 131,
      "b": 241
    }
  }
}

