/* This index.js file was itself autogenerated; run `make` in kb-styles to rebuild */



module.exports = {
  "colors": {
    "blue": {
      "css": "rgb(76,142,255)",
      "r": 76,
      "g": 142,
      "b": 255
    },
    "blue_dark": {
      "css": "rgb(54,99,234)",
      "r": 54,
      "g": 99,
      "b": 234
    },
    "blue_darker": {
      "css": "rgb(16,54,172)",
      "r": 16,
      "g": 54,
      "b": 172
    },
    "blue_darker2": {
      "css": "rgb(24,45,110)",
      "r": 24,
      "g": 45,
      "b": 110
    },
    "blue_light": {
      "css": "rgb(115,166,255)",
      "r": 115,
      "g": 166,
      "b": 255
    },
    "blue_lighter": {
      "css": "rgb(168,204,255)",
      "r": 168,
      "g": 204,
      "b": 255
    },
    "blue_lighter2": {
      "css": "rgb(235,242,252)",
      "r": 235,
      "g": 242,
      "b": 252
    },
    "blue_lighter3": {
      "css": "rgb(247,249,252)",
      "r": 247,
      "g": 249,
      "b": 252
    },
    "orange": {
      "css": "rgb(255,111,33)",
      "r": 255,
      "g": 111,
      "b": 33
    },
    "yellow": {
      "css": "rgb(255,247,90)",
      "r": 255,
      "g": 247,
      "b": 90
    },
    "yellow_dark": {
      "css": "rgb(255,184,0)",
      "r": 255,
      "g": 184,
      "b": 0
    },
    "yellow_light": {
      "css": "rgb(255,253,204)",
      "r": 255,
      "g": 253,
      "b": 204
    },
    "green": {
      "css": "rgb(55,189,153)",
      "r": 55,
      "g": 189,
      "b": 153
    },
    "green_dark": {
      "css": "rgb(24,158,122)",
      "r": 24,
      "g": 158,
      "b": 122
    },
    "green_darker": {
      "css": "rgb(18,120,93)",
      "r": 18,
      "g": 120,
      "b": 93
    },
    "green_light": {
      "css": "rgb(183,238,217)",
      "r": 183,
      "g": 238,
      "b": 217
    },
    "green_lighter": {
      "css": "rgb(232,250,246)",
      "r": 232,
      "g": 250,
      "b": 246
    },
    "red": {
      "css": "rgb(231,249,246)",
      "r": 231,
      "g": 249,
      "b": 246
    },
    "red_dark": {
      "css": "rgb(235,37,59)",
      "r": 235,
      "g": 37,
      "b": 59
    },
    "red_darker": {
      "css": "rgb(189,11,31)",
      "r": 189,
      "g": 11,
      "b": 31
    },
    "red_light": {
      "css": "rgb(255,202,193)",
      "r": 255,
      "g": 202,
      "b": 193
    },
    "red_lighter": {
      "css": "rgb(250,242,237)",
      "r": 250,
      "g": 242,
      "b": 237
    },
    "grey_light": {
      "css": "rgb(246,246,246)",
      "r": 246,
      "g": 246,
      "b": 246
    },
    "grey": {
      "css": "rgb(230,230,230)",
      "r": 230,
      "g": 230,
      "b": 230
    },
    "grey_dark": {
      "css": "rgb(204,204,204)",
      "r": 204,
      "g": 204,
      "b": 204
    },
    "purple": {
      "css": "rgb(132,92,219)",
      "r": 132,
      "g": 92,
      "b": 219
    },
    "purple_dark": {
      "css": "rgb(112,78,186)",
      "r": 112,
      "g": 78,
      "b": 186
    },
    "purple_light": {
      "css": "rgb(159,123,236)",
      "r": 159,
      "g": 123,
      "b": 236
    },
    "background_grey_light": {
      "css": "rgb(246,246,246)",
      "r": 246,
      "g": 246,
      "b": 246
    },
    "background_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "brown": {
      "css": "rgb(71,31,18)",
      "r": 71,
      "g": 31,
      "b": 18
    },
    "white5": {
      "css": "rgba(255,255,255,0.050)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.05
    },
    "white5_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white5_on_black": {
      "css": "rgb(12,12,12)",
      "r": 12,
      "g": 12,
      "b": 12
    },
    "white5_on_yellow": {
      "css": "rgb(255,247,98)",
      "r": 255,
      "g": 247,
      "b": 98
    },
    "white5_on_blue_darker2": {
      "css": "rgb(35,55,117)",
      "r": 35,
      "g": 55,
      "b": 117
    },
    "white10": {
      "css": "rgba(255,255,255,0.100)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.1
    },
    "white10_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white10_on_black": {
      "css": "rgb(25,25,25)",
      "r": 25,
      "g": 25,
      "b": 25
    },
    "white10_on_yellow": {
      "css": "rgb(255,247,106)",
      "r": 255,
      "g": 247,
      "b": 106
    },
    "white10_on_blue_darker2": {
      "css": "rgb(47,66,124)",
      "r": 47,
      "g": 66,
      "b": 124
    },
    "white20": {
      "css": "rgba(255,255,255,0.200)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.2
    },
    "white20_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white20_on_black": {
      "css": "rgb(51,51,51)",
      "r": 51,
      "g": 51,
      "b": 51
    },
    "white20_on_yellow": {
      "css": "rgb(255,248,123)",
      "r": 255,
      "g": 248,
      "b": 123
    },
    "white20_on_blue_darker2": {
      "css": "rgb(70,87,139)",
      "r": 70,
      "g": 87,
      "b": 139
    },
    "white50": {
      "css": "rgba(255,255,255,0.500)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.5
    },
    "white50_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white50_on_black": {
      "css": "rgb(127,127,127)",
      "r": 127,
      "g": 127,
      "b": 127
    },
    "white50_on_yellow": {
      "css": "rgb(255,251,172)",
      "r": 255,
      "g": 251,
      "b": 172
    },
    "white50_on_blue_darker2": {
      "css": "rgb(139,150,182)",
      "r": 139,
      "g": 150,
      "b": 182
    },
    "white63": {
      "css": "rgba(255,255,255,0.630)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.63
    },
    "white63_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white63_on_black": {
      "css": "rgb(160,160,160)",
      "r": 160,
      "g": 160,
      "b": 160
    },
    "white63_on_yellow": {
      "css": "rgb(255,252,193)",
      "r": 255,
      "g": 252,
      "b": 193
    },
    "white63_on_blue_darker2": {
      "css": "rgb(169,177,201)",
      "r": 169,
      "g": 177,
      "b": 201
    },
    "white85": {
      "css": "rgba(255,255,255,0.850)",
      "r": 255,
      "g": 255,
      "b": 255,
      "a": 0.85
    },
    "white85_on_white": {
      "css": "rgb(255,255,255)",
      "r": 255,
      "g": 255,
      "b": 255
    },
    "white85_on_black": {
      "css": "rgb(216,216,216)",
      "r": 216,
      "g": 216,
      "b": 216
    },
    "white85_on_yellow": {
      "css": "rgb(255,253,230)",
      "r": 255,
      "g": 253,
      "b": 230
    },
    "white85_on_blue_darker2": {
      "css": "rgb(220,223,233)",
      "r": 220,
      "g": 223,
      "b": 233
    },
    "black5": {
      "css": "rgba(0,0,0,0.050)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.05
    },
    "black5_on_white": {
      "css": "rgb(242,242,242)",
      "r": 242,
      "g": 242,
      "b": 242
    },
    "black5_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black5_on_yellow": {
      "css": "rgb(242,234,85)",
      "r": 242,
      "g": 234,
      "b": 85
    },
    "black5_on_blue_darker2": {
      "css": "rgb(22,42,104)",
      "r": 22,
      "g": 42,
      "b": 104
    },
    "black10": {
      "css": "rgba(0,0,0,0.100)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.1
    },
    "black10_on_white": {
      "css": "rgb(229,229,229)",
      "r": 229,
      "g": 229,
      "b": 229
    },
    "black10_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black10_on_yellow": {
      "css": "rgb(229,222,81)",
      "r": 229,
      "g": 222,
      "b": 81
    },
    "black10_on_blue_darker2": {
      "css": "rgb(21,40,99)",
      "r": 21,
      "g": 40,
      "b": 99
    },
    "black20": {
      "css": "rgba(0,0,0,0.200)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.2
    },
    "black20_on_white": {
      "css": "rgb(204,204,204)",
      "r": 204,
      "g": 204,
      "b": 204
    },
    "black20_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black20_on_yellow": {
      "css": "rgb(204,197,72)",
      "r": 204,
      "g": 197,
      "b": 72
    },
    "black20_on_blue_darker2": {
      "css": "rgb(19,36,88)",
      "r": 19,
      "g": 36,
      "b": 88
    },
    "black50": {
      "css": "rgba(0,0,0,0.500)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.5
    },
    "black50_on_white": {
      "css": "rgb(127,127,127)",
      "r": 127,
      "g": 127,
      "b": 127
    },
    "black50_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black50_on_yellow": {
      "css": "rgb(127,123,45)",
      "r": 127,
      "g": 123,
      "b": 45
    },
    "black50_on_blue_darker2": {
      "css": "rgb(12,22,55)",
      "r": 12,
      "g": 22,
      "b": 55
    },
    "black63": {
      "css": "rgba(0,0,0,0.630)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.63
    },
    "black63_on_white": {
      "css": "rgb(94,94,94)",
      "r": 94,
      "g": 94,
      "b": 94
    },
    "black63_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black63_on_yellow": {
      "css": "rgb(94,91,33)",
      "r": 94,
      "g": 91,
      "b": 33
    },
    "black63_on_blue_darker2": {
      "css": "rgb(8,16,40)",
      "r": 8,
      "g": 16,
      "b": 40
    },
    "black85": {
      "css": "rgba(0,0,0,0.850)",
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.85
    },
    "black85_on_white": {
      "css": "rgb(38,38,38)",
      "r": 38,
      "g": 38,
      "b": 38
    },
    "black85_on_black": {
      "css": "rgb(0,0,0)",
      "r": 0,
      "g": 0,
      "b": 0
    },
    "black85_on_yellow": {
      "css": "rgb(38,37,13)",
      "r": 38,
      "g": 37,
      "b": 13
    },
    "black85_on_blue_darker2": {
      "css": "rgb(3,6,16)",
      "r": 3,
      "g": 6,
      "b": 16
    },
    "brown5": {
      "css": "rgba(71,31,18,0.050)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.05
    },
    "brown5_on_white": {
      "css": "rgb(245,243,243)",
      "r": 245,
      "g": 243,
      "b": 243
    },
    "brown5_on_black": {
      "css": "rgb(3,1,0)",
      "r": 3,
      "g": 1,
      "b": 0
    },
    "brown5_on_yellow": {
      "css": "rgb(245,236,86)",
      "r": 245,
      "g": 236,
      "b": 86
    },
    "brown5_on_blue_darker2": {
      "css": "rgb(26,44,105)",
      "r": 26,
      "g": 44,
      "b": 105
    },
    "brown10": {
      "css": "rgba(71,31,18,0.100)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.1
    },
    "brown10_on_white": {
      "css": "rgb(236,232,231)",
      "r": 236,
      "g": 232,
      "b": 231
    },
    "brown10_on_black": {
      "css": "rgb(7,3,1)",
      "r": 7,
      "g": 3,
      "b": 1
    },
    "brown10_on_yellow": {
      "css": "rgb(236,225,82)",
      "r": 236,
      "g": 225,
      "b": 82
    },
    "brown10_on_blue_darker2": {
      "css": "rgb(28,43,100)",
      "r": 28,
      "g": 43,
      "b": 100
    },
    "brown20": {
      "css": "rgba(71,31,18,0.200)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.2
    },
    "brown20_on_white": {
      "css": "rgb(218,210,207)",
      "r": 218,
      "g": 210,
      "b": 207
    },
    "brown20_on_black": {
      "css": "rgb(14,6,3)",
      "r": 14,
      "g": 6,
      "b": 3
    },
    "brown20_on_yellow": {
      "css": "rgb(218,203,75)",
      "r": 218,
      "g": 203,
      "b": 75
    },
    "brown20_on_blue_darker2": {
      "css": "rgb(33,42,91)",
      "r": 33,
      "g": 42,
      "b": 91
    },
    "brown50": {
      "css": "rgba(71,31,18,0.500)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.5
    },
    "brown50_on_white": {
      "css": "rgb(163,143,136)",
      "r": 163,
      "g": 143,
      "b": 136
    },
    "brown50_on_black": {
      "css": "rgb(35,15,9)",
      "r": 35,
      "g": 15,
      "b": 9
    },
    "brown50_on_yellow": {
      "css": "rgb(163,139,54)",
      "r": 163,
      "g": 139,
      "b": 54
    },
    "brown50_on_blue_darker2": {
      "css": "rgb(47,38,64)",
      "r": 47,
      "g": 38,
      "b": 64
    },
    "brown63": {
      "css": "rgba(71,31,18,0.630)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.63
    },
    "brown63_on_white": {
      "css": "rgb(139,113,105)",
      "r": 139,
      "g": 113,
      "b": 105
    },
    "brown63_on_black": {
      "css": "rgb(44,19,11)",
      "r": 44,
      "g": 19,
      "b": 11
    },
    "brown63_on_yellow": {
      "css": "rgb(139,110,44)",
      "r": 139,
      "g": 110,
      "b": 44
    },
    "brown63_on_blue_darker2": {
      "css": "rgb(53,36,52)",
      "r": 53,
      "g": 36,
      "b": 52
    },
    "brown85": {
      "css": "rgba(71,31,18,0.850)",
      "r": 71,
      "g": 31,
      "b": 18,
      "a": 0.85
    },
    "brown85_on_white": {
      "css": "rgb(98,64,53)",
      "r": 98,
      "g": 64,
      "b": 53
    },
    "brown85_on_black": {
      "css": "rgb(60,26,15)",
      "r": 60,
      "g": 26,
      "b": 15
    },
    "brown85_on_yellow": {
      "css": "rgb(98,63,28)",
      "r": 98,
      "g": 63,
      "b": 28
    },
    "brown85_on_blue_darker2": {
      "css": "rgb(63,33,31)",
      "r": 63,
      "g": 33,
      "b": 31
    },
    "blue5": {
      "css": "rgba(76,142,255,0.050)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.05
    },
    "blue5_on_white": {
      "css": "rgb(246,249,255)",
      "r": 246,
      "g": 249,
      "b": 255
    },
    "blue5_on_black": {
      "css": "rgb(3,7,12)",
      "r": 3,
      "g": 7,
      "b": 12
    },
    "blue5_on_yellow": {
      "css": "rgb(246,241,98)",
      "r": 246,
      "g": 241,
      "b": 98
    },
    "blue5_on_blue_darker2": {
      "css": "rgb(26,49,117)",
      "r": 26,
      "g": 49,
      "b": 117
    },
    "blue10": {
      "css": "rgba(76,142,255,0.100)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.1
    },
    "blue10_on_white": {
      "css": "rgb(237,243,255)",
      "r": 237,
      "g": 243,
      "b": 255
    },
    "blue10_on_black": {
      "css": "rgb(7,14,25)",
      "r": 7,
      "g": 14,
      "b": 25
    },
    "blue10_on_yellow": {
      "css": "rgb(237,236,106)",
      "r": 237,
      "g": 236,
      "b": 106
    },
    "blue10_on_blue_darker2": {
      "css": "rgb(29,54,124)",
      "r": 29,
      "g": 54,
      "b": 124
    },
    "blue20": {
      "css": "rgba(76,142,255,0.200)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.2
    },
    "blue20_on_white": {
      "css": "rgb(219,232,255)",
      "r": 219,
      "g": 232,
      "b": 255
    },
    "blue20_on_black": {
      "css": "rgb(15,28,51)",
      "r": 15,
      "g": 28,
      "b": 51
    },
    "blue20_on_yellow": {
      "css": "rgb(219,226,123)",
      "r": 219,
      "g": 226,
      "b": 123
    },
    "blue20_on_blue_darker2": {
      "css": "rgb(34,64,139)",
      "r": 34,
      "g": 64,
      "b": 139
    },
    "blue50": {
      "css": "rgba(76,142,255,0.500)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.5
    },
    "blue50_on_white": {
      "css": "rgb(165,198,255)",
      "r": 165,
      "g": 198,
      "b": 255
    },
    "blue50_on_black": {
      "css": "rgb(38,71,127)",
      "r": 38,
      "g": 71,
      "b": 127
    },
    "blue50_on_yellow": {
      "css": "rgb(165,194,172)",
      "r": 165,
      "g": 194,
      "b": 172
    },
    "blue50_on_blue_darker2": {
      "css": "rgb(50,93,182)",
      "r": 50,
      "g": 93,
      "b": 182
    },
    "blue63": {
      "css": "rgba(76,142,255,0.630)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.63
    },
    "blue63_on_white": {
      "css": "rgb(142,183,255)",
      "r": 142,
      "g": 183,
      "b": 255
    },
    "blue63_on_black": {
      "css": "rgb(47,89,160)",
      "r": 47,
      "g": 89,
      "b": 160
    },
    "blue63_on_yellow": {
      "css": "rgb(142,180,193)",
      "r": 142,
      "g": 180,
      "b": 193
    },
    "blue63_on_blue_darker2": {
      "css": "rgb(56,106,201)",
      "r": 56,
      "g": 106,
      "b": 201
    },
    "blue85": {
      "css": "rgba(76,142,255,0.850)",
      "r": 76,
      "g": 142,
      "b": 255,
      "a": 0.85
    },
    "blue85_on_white": {
      "css": "rgb(102,158,255)",
      "r": 102,
      "g": 158,
      "b": 255
    },
    "blue85_on_black": {
      "css": "rgb(64,120,216)",
      "r": 64,
      "g": 120,
      "b": 216
    },
    "blue85_on_yellow": {
      "css": "rgb(102,157,230)",
      "r": 102,
      "g": 157,
      "b": 230
    },
    "blue85_on_blue_darker2": {
      "css": "rgb(68,127,233)",
      "r": 68,
      "g": 127,
      "b": 233
    }
  }
}

